### ISSUE TITLE
Use cache for composer dependencies

### ISSUE THREAD

**Issue by wijourdil** [wijourdil/project-setup#16]
Add the following block in the `style-fix.yml` stub
```yaml
      # Cache composer dependencies
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
```
